use db;
insert into users values (1, 'Łódź', '25', 'Piotrkowska', 'test@test.com', 'nick', 'hasło');
insert into authors values (1, "Adam Mickiewicz");
insert into author_book values (1, 1);
insert into books values (1, 'Pan Tadeusz', 2015,  1);
insert into books values (2, 'pan Tadeusz', 2015,  1);
insert into books values (3, 'Pan tadeusz', 2015,  1);
insert into books values (4, 'Pan Tadeusz', 2015,  1);
insert into books values (5, 'PanTadeusz', 2015,  1);
insert into books values (6, 'Pan Tadeusz', 2015,  1);